SELECT
    employee_id,
    MonthlyIncome,
    DailyRate,
    HourlyRate,
    MonthlyRate,
    JobSatisfaction,
    {{ satisfaction_label('JobSatisfaction') }} AS job_satisfaction_label,
    EnvironmentSatisfaction,
    WorkLifeBalance,
    RelationshipSatisfaction,
    PerformanceRating,
    PercentSalaryHike,
    YearsAtCompany,
    YearsInCurrentRole,
    YearsSinceLastPromotion,
    YearsWithCurrManager,
    TotalWorkingYears,
    NumCompaniesWorked,
    TrainingTimesLastYear,
    StockOptionLevel
FROM {{ ref('stg_employees') }}